config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts

  get ':user_name', to: 'profiles#show', as: :profile
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  #to avoid adding default image
  belongs_to :user

  validates :user_id, presence: true
  validates :image, presence: true

  has_attached_file :image,  styles: { medium: "450x450" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/models/user.rb
class User < ApplicationRecord
  validates :user_name, presence: true, length: {minimum: 4, maximum: 16}
  
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :is_owned, only: [:edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @posts = Post.order(name: :asc).paginate(page: params[:page], per_page: 2)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = current_user.posts.build
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:image, :caption)
    end

    def is_owned
      unless current_user == @post.user
      flash[:alert] = "Not your post!!!"
      redirect_to root_path
      end
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @posts = User.find_by(user_name: params[:user_name]).posts.order('created_at DESC')
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <header class = "navbar">
      <%= link_to  'Instagram', '/' , class: "navbar-logo"%>
    <% if user_signed_in? %>
      <%= link_to "New Post", new_post_path, class: "navbar-links" %>
      <%= link_to "My Profile", profile_path(current_user.user_name), class: "navbar-links" %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete , class: "navbar-links"%>
    <% else %>
      <%= link_to "Login", new_user_session_path, class: "navbar-links" %>
      <%= link_to "Register", new_user_registration_path ,class: "navbar-links" %>
    <%end%>
    </header>
    
    <%= yield %>
</body>

</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :caption %>
    <%= form.text_field :caption %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="feed">
    <div class="feed-post-username">
      <%= link_to post.user.user_name, profile_path(post.user.user_name) %>
    </div>
    <div class="feed-post-image">
      <%= link_to (image_tag post.image.url(:medium)), post_path(post) %>
    </div>
    <div class="feed-post-caption">
      <%= post.caption%>
    </div>
  </div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div id="posts">
	<% @posts.each do |post| %>
	  <%= render 'post', post: post %>
	<% end %>
</div>
<div id="infinite-scrolling">
  <%= will_paginate @posts %>
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript render(@posts) %>');
<% if @posts.next_page %>
	$('.pagination').replaceWith('<%= escape_javascript will_paginate(@posts) %>');
<% else %>
	$('.pagination').remove();
<% end %> 

console.log("index")

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="show-post">
    <div class = "show-post-image" >
        <%= image_tag @post.image.url(:medium)%>
    </div>
    <div class = "show-post-caption">
        <%= @post.caption%>
    </div>
    <div class = "show-post-options">
    <%if @post.user.id == current_user.id %>
      <span><%= link_to 'Edit', edit_post_path(@post) %></span>
      <span><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></span>
    <%end%>
    </div>
</div>

app/views/profiles/show.html.erb
<h1 class = "profile-username">
  <%= current_user.user_name%>
</h1>

<div class = "feed">
  <% @posts.each do |post| %>
    <div class = "feed-post-image">
      <%= link_to (image_tag post.image.url(:medium)),post_path(post)%>
    </div>
    <div class="feed-post-caption">
      <%= post.caption%>
    </div>
  <% end %>
</div>